### ISSUE TITLE
CuppaAlert / Restore window scroll position

### ISSUE THREAD

**Issue by schube** [cloudbit-interactive/cuppajs#1]
Hi! 

Thank you for your great library!

I have a little problem with CuppaAlert. At the bottom of a long page I have a button which triggers the alert. The alert is shown (and the the website in the background is scrolled up to the top). When I close the alert, the website is still scrolled up. Is there any way to preserve/restore the scroll position?

Thank you!

**Comment by tufik2** [comment]
Hi @schube, I was trying to reproduce the issue but it was not possible, are you sure that the problem is the component?
If you check [this doc](https://cuppajs.cloudbit.co/#/cuppa-alert), you will see that alert is not modifying the page scroll position.

Is it possible for you to replicate the issue in CodePen or any similar online tool?, so I will be able to check the issue and fix the bug if necessary.

Also, a quick solution for you will be to capture the scroll position with JS before add the alert and restore the scroll to that position after close the alert, you can use the **callback** event to know when alert is closed

**Comment by schube** [comment]
Hi @tufik2, thank you for your fast reply. I tried it with Safari and Chrome v106 and with the debugger on, the scroll (or better "jump") to the page start happens when this line is executed: `document.body.append(alert);`. Alert beeing 

~~~
let alert = new CuppaAlert({`
        	title: _this.data('message-title'),
        	message: _this.data('message-confirm'),
        	backdropEnabled: true,
        	acceptText: 'Ja',
        	cancelText: 'Nein',
        	callback:(res)=>{
				console.log(res);
				if(res.value==true) {
					onConfirm();
				}
        	
        	}
    	});
~~~

I will try to create a CodePen to reproduce this soon.
Thank you!

**Comment by schube** [comment]
Okay, I tried to reproduce the problem and you are right, when I use ONLY cuppa, the scroll position does not change.
So I will further dig into the problem and will report back.

**Comment by schube** [comment]
I think I found the problem, but I am not 100% sure yet where to look for the solution:

The website has this CSS style definition like that:

~~~
html, body {
	height: 100%;
}
~~~

And this results in the behavior described. You can test it here: https://kunden.schubec.com/cuppa/

So this is more a CSS problem I guess and not really related to cuppa. I guess, cuppa also cannot do much there.
I don't know why the style is defined like that. I guess that is a left over from my predecessor.

So sorry for bothering you and thanks for your cool component(s)!

Best,
Bernhard
